# Generated by Django 4.2.7 on 2025-11-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0003_bloodbank_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='bloodbank',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
