# Generated by Django 5.2.7 on 2025-11-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0005_campregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='campregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended')], default='approved', max_length=20),
        ),
    ]
