# Generated by Django 4.2.7 on 2025-11-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='request_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
