# Generated by Django 4.2.7 on 2025-11-05 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank', '0004_alter_bloodbank_address_alter_bloodbank_city_and_more'),
        ('requests', '0002_bloodrequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='bloodbank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='bloodbank.bloodbank'),
        ),
    ]
