"""
Django settings for ebloodbank project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
try:
    from decouple import config  # type: ignore
except ImportError:
    # Minimal fallback if python-decouple isn't installed
    def config(key, default=None, cast=None):
        val = os.environ.get(key)
        if val is None:
            return default
        if cast is bool:
            return str(val).lower() in ("1", "true", "yes", "on")
        return val
from datetime import timedelta
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-!#%x*v0p8t$-qi^cr8@cx!rfc6^^yhxsjp9k0n#lpdhlf*+1*c')

# SECURITY WARNING: don't run with debug turned on in production!
# Make DEBUG casting robust so unusual values like "warn" don't crash startup.
try:
    DEBUG = config('DEBUG', cast=bool, default=True)
except ValueError:
    raw_debug = os.environ.get('DEBUG', '')
    if isinstance(raw_debug, str) and raw_debug:
        DEBUG = raw_debug.lower() in ('1', 'true', 'yes', 'on', 'debug')
    else:
        DEBUG = bool(raw_debug)

# ALLOWED_HOSTS - can be set via environment variable (comma-separated)
# Default includes localhost for development
allowed_hosts_str = config('ALLOWED_HOSTS', default='localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_str.split(',') if h.strip()]

# Add Render domain if we're on Render (detected by RENDER environment variable)
# Also add common Render domain patterns
if not any('onrender.com' in host for host in ALLOWED_HOSTS):
    ALLOWED_HOSTS.append('e-bloodbank.onrender.com')
    # Allow any onrender.com subdomain
    if os.environ.get('RENDER'):
        # On Render, allow the service domain
        render_service_name = os.environ.get('RENDER_SERVICE_NAME', 'e-bloodbank')
        ALLOWED_HOSTS.append(f'{render_service_name}.onrender.com')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'django_filters',
    # Local apps
    'accounts.apps.AccountsConfig',
    'bloodbank',
    'inventory',
    'donors',
    'requests',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ebloodbank.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'ebloodbank' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ebloodbank.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Parse DATABASE_URL from environment (provided by Render, Heroku, etc.)
# Format: postgresql://user:password@host:port/dbname
database_url = config('DATABASE_URL', default=None)

if database_url:
    # Use dj-database-url to parse the DATABASE_URL
    DATABASES = {
        'default': dj_database_url.parse(database_url, conn_max_age=600)
    }
    # Ensure connect_timeout is set
    if 'OPTIONS' not in DATABASES['default']:
        DATABASES['default']['OPTIONS'] = {}
    DATABASES['default']['OPTIONS']['connect_timeout'] = 10
    # For Render PostgreSQL, ensure SSL is enabled if not already set
    # Render databases typically require SSL connections
    if 'sslmode' not in DATABASES['default']['OPTIONS']:
        # Check if we're on Render (they provide RENDER environment variable)
        if os.environ.get('RENDER'):
            DATABASES['default']['OPTIONS']['sslmode'] = 'require'
else:
    # Local development: use SQLite by default to avoid requiring PostgreSQL.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,
        }
    },
    {
        'NAME': 'accounts.password_validators.MaximumLengthValidator',
        'OPTIONS': {
            'max_length': 4096,
        }
    },
    {
        'NAME': 'accounts.password_validators.UppercaseValidator',
    },
    {
        'NAME': 'accounts.password_validators.LowercaseValidator',
    },
    {
        'NAME': 'accounts.password_validators.NumericValidator',
    },
    {
        'NAME': 'accounts.password_validators.SpecialCharacterValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}


CORS_ALLOWED_ORIGINS = [
    o.strip() for o in config(
        'CORS_ALLOWED_ORIGINS',
        default='http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:5177,http://127.0.0.1:5173,http://127.0.0.1:5174,http://127.0.0.1:5175,http://127.0.0.1:5176,http://127.0.0.1:5177,http://localhost:3000,https://e-blood-bank-pi.vercel.app'
    ).split(',') if o.strip()
]
CORS_ALLOW_CREDENTIALS = True

# In local development, Vite may choose a different port (e.g. 5174, 5177) if 5173 is busy.
# Allow any localhost port when DEBUG=True to avoid "Network Error" from CORS blocking.
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http://localhost:\d+$",
        r"^http://127\.0\.0\.1:\d+$",
    ]

# When frontend uses Vite proxy, requests reach Django with Referer from frontend origin.
# Trust these origins for CSRF to avoid 403 on POST.
if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:5173', 'http://127.0.0.1:5173',
        'http://localhost:5174', 'http://127.0.0.1:5174',
        'http://localhost:5175', 'http://127.0.0.1:5175',
        'http://localhost:5176', 'http://127.0.0.1:5176',
        'http://localhost:5177', 'http://127.0.0.1:5177',
        'http://localhost:3000', 'http://127.0.0.1:3000',
    ]

# Email Configuration
# Default to SMTP backend for real email sending
# To use console backend for development, set EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend in .env
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER or 'noreply@ebloodbank.com')
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=10, cast=int)


# Cache Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

